# Generated by Django 5.2.10 on 2026-03-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
