# Generated by Django 5.2.10 on 2026-02-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('sent_post_dhl', 'Sent per Post/DHL'), ('waiting_approval', 'Waiting Client Approval'), ('approved', 'Approved'), ('closed', 'Closed')], default='open', max_length=30),
        ),
    ]
